# =============================================================================
# Ansible Inventory - ALU Graduates Empowerment Platform
# BASTION_IP and APP_VM_PRIVATE_IP are replaced by cd.yml at deploy time
# =============================================================================
[app_server]
alu-platform ansible_host=APP_VM_PRIVATE_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/alu-platform-key.pem

[app_server:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ~/.ssh/alu-platform-key.pem -W %h:%p -o StrictHostKeyChecking=no ubuntu@BASTION_IP"'