# =============================================================================
# Ansible Inventory - ALU Graduates Empowerment Platform
# Replace SERVER_IP with the output from Terraform (instance_public_ip)
# =============================================================================

[app_servers]
alu-platform ansible_host=app_server

[app_servers:vars]
ansible_python_interpreter=/usr/bin/python3


